include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

#region client

push client image to test artifact registry:
  stage: push images
  needs:
    - job: build client docker image for test
      artifacts: true
      optional: true
  extends:
    - .gcp_eu_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - docker load -i client/image-test.tar
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner/spinner-client-test:latest ${GCP_REGISTRY_URL}/spinner-client:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-client:$CI_COMMIT_SHORT_SHA
    - docker tag spinner/spinner-client-test:latest ${GCP_REGISTRY_URL}/spinner-client:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-client:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - gitlab-ci/stages/03-push-images.yml
      when: manual
      allow_failure: true
    - !reference [.rules, on_merge_to_master]

push client image to production artifact registry:
  stage: push images
  needs:
    - job: build client docker image for production
      artifacts: true
      optional: true
  extends:
    - .gcp_eu_production_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - docker load -i client/image-production.tar
    - docker tag spinner/spinner-client-production:latest ${GCP_REGISTRY_URL}/spinner-client:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-client:$CI_COMMIT_SHORT_SHA
    - docker tag spinner/spinner-client-production:latest ${GCP_REGISTRY_URL}/spinner-client:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-client:latest
  rules:
    - !reference [.rules, on_merge_to_prod]

#endregion

#region server

push server image to test artifact registry:
  stage: push images
  needs:
    - job: build server docker image
      artifacts: true
      optional: true
  extends:
    - .gcp_eu_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - docker load -i server/image.tar
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker tag spinner/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-server:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - gitlab-ci/stages/03-push-images.yml
      when: manual
      allow_failure: true
    - !reference [.rules, on_merge_to_master]

push server image to production artifact registry:
  stage: push images
  needs:
    - job: build server docker image
      artifacts: true
      optional: true
  extends:
    - .gcp_eu_production_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - docker load -i server/image.tar
    - docker tag spinner/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker tag spinner/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-server:latest
  rules:
    - !reference [.rules, on_merge_to_prod]

#endregion

#region scratch-git

push scratch-git image to test artifact registry:
  stage: push images
  needs:
    - job: build scratch-git docker image
      artifacts: true
      optional: true
  extends:
    - .gcp_eu_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - docker load -i scratch-git-2/image.tar
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner/spinner-scratch-git:latest ${GCP_REGISTRY_URL}/spinner-scratch-git:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-scratch-git:$CI_COMMIT_SHORT_SHA
    - docker tag spinner/spinner-scratch-git:latest ${GCP_REGISTRY_URL}/spinner-scratch-git:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-scratch-git:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - gitlab-ci/stages/03-push-images.yml
      when: manual
      allow_failure: true
    - !reference [.rules, on_merge_to_master]

push scratch-git image to production artifact registry:
  stage: push images
  needs:
    - job: build scratch-git docker image
      artifacts: true
      optional: true
  extends:
    - .gcp_eu_production_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - docker load -i scratch-git-2/image.tar
    - docker tag spinner/spinner-scratch-git:latest ${GCP_REGISTRY_URL}/spinner-scratch-git:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-scratch-git:$CI_COMMIT_SHORT_SHA
    - docker tag spinner/spinner-scratch-git:latest ${GCP_REGISTRY_URL}/spinner-scratch-git:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-scratch-git:latest
  rules:
    - !reference [.rules, on_merge_to_prod]
#endregion
