include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - "/gitlab-ci/common.yml"
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/local-runners.yml"
  - "/gitlab-ci/stages/01-build-and-test.yml"
  - "/gitlab-ci/stages/01-smoke-tests.yml"
  - "/gitlab-ci/stages/01-cli-integration-tests.yml"
  - "/gitlab-ci/stages/02-push-to-prod.yml"
  - "/gitlab-ci/stages/03-push-images.yml"
  - "/gitlab-ci/stages/04-run-migrations.yml"
  - "/gitlab-ci/stages/05-deploy.yml"
  - "/gitlab-ci/stages/06-environment-tests.yml"
  - "scratch-git-2/.gitlab-ci-release.yml"
  - "scratch-desktop/.gitlab-ci-release.yml"
