import { TSchema } from '@sinclair/typebox';
import type { EntityId } from '@spinner/shared-types';
import { PostgresColumnType } from '@spinner/shared-types';

// Re-export from shared-types for backwards compatibility
export { PostgresColumnType };
export type { EntityId };

export type TablePreview = {
  id: EntityId;
  displayName: string;
  /** The table is not available to be read from
   * e.g. A supabase table without a unique column.
   */
  disabled?: true;
  /** Tables that don't have an autogenerated id column — creates are not supported */
  disabledCreates?: true;
  metadata?: Record<string, unknown>;
};

export type BaseJsonTableSpec = {
  id: EntityId;
  slug: string;
  name: string;
  schema: TSchema;
  // The remoteId of the column that should be used as the id column for visualizing records
  // This is used to identify the record in the connector.
  // This is usually the id column, but it can be different for some connectors id vs Id, etc.
  idColumnRemoteId: string;
  // The remoteId of the column that should be used as the title/header column for visualizing records
  titleColumnRemoteId?: EntityId['remoteId'];
  // The remoteId of the column that should be used as the main content/body in MD view
  // This is used to display the main content of the record in the MD view.
  mainContentColumnRemoteId?: EntityId['remoteId'];
  // Dot-path to the field in a raw record whose value should be used as the filename slug.
  // When set, files will be named `<slug>.json` instead of `<id>.json`.
  // Example: 'fieldData.slug' for Webflow records.
  slugColumnRemoteId?: string;
};

/**
 * Generic representation of a record file from a connector
 * This lets us know when we are talking about record files instead of using the generic Record<string, unknown> type.
 */
export type ConnectorFile = Record<string, unknown>;

export type ConnectorErrorDetails = {
  userFriendlyMessage: string;
  description?: string;
  additionalContext?: Record<string, unknown>;
};

export type RecordErrorsMetadata = {
  // TODO: Add record-level here if needed.

  /** Indexed by the WSID of the field */
  byField?: Record<string, { message: string; severity: 'warning' | 'error' }[]>;
};
