import { TSchema } from '@sinclair/typebox';
import type { EntityId } from '@spinner/shared-types';
import { PostgresColumnType } from '@spinner/shared-types';
import { get, set, unset } from 'lodash';

// Re-export from shared-types for backwards compatibility
export { PostgresColumnType };
export type { EntityId };

export type TablePreview = {
  id: EntityId;
  displayName: string;
  /** The table is not available to be read from
   * e.g. A supabase table without a unique column.
   */
  disabled?: true;
  /** Tables that don't have an autogenerated id column — creates are not supported */
  disabledCreates?: true;
  /** Slash-separated path for grouping tables in the UI (e.g. "My Project/public") */
  parentPath?: string;
  /** Human-readable reason why this table is disabled or has creates disabled */
  disabledReason?: string;
  metadata?: Record<string, unknown>;
};

/**
 * A lodash-style dot path into a record file pointing at the value used as
 * its remote id (e.g. `'id'` for flat ids, `'id.record_id'` for Attio's id
 * triple). Branded so callers must construct it via `idPath(...)` and can't
 * accidentally pass a plain string.
 */
export type IdPath = string & { readonly __idPath: unique symbol };

/**
 * Construct an `IdPath` from a lodash-style dot path string. Use at every site
 * a connector schema declares its `idColumnRemoteId`.
 */
export function idPath(path: string): IdPath {
  return path as IdPath;
}

/**
 * Read the raw value at a record's id path. Preserves the native JSON type so
 * callers that need to detect special markers (e.g. pending-publish sentinels)
 * or write the value back into a file via `lodash.set` see exactly what's on
 * disk. Use `readRecordIdAsString` when you need a string for index/lookup.
 */
export function readRecordId(record: Record<string, unknown>, idPath: IdPath): unknown {
  return get(record, idPath);
}

/**
 * Read a record's id and coerce it to a string for use as a file-index key,
 * remote-id lookup, or filename. Returns `null` if the value at the path is
 * missing or is neither a string nor a finite number — callers that want a
 * string fallback typically write `readRecordIdAsString(...) ?? ''`.
 */
export function readRecordIdAsString(record: Record<string, unknown>, idPath: IdPath): string | null {
  const v = readRecordId(record, idPath);
  if (typeof v === 'string') return v;
  if (typeof v === 'number' && Number.isFinite(v)) return String(v);
  return null;
}

/**
 * Write a value at a record's id path. Mutates the record in place. Use when
 * recovering an id that was missing from the file content (filename-index
 * fallback) so the connector and git see a consistent value before the write.
 */
export function writeRecordId(record: Record<string, unknown>, idPath: IdPath, value: string | number): void {
  set(record, idPath, value);
}

/**
 * Remove the value at a record's id path. Mutates the record in place. Used
 * to strip pending-publish sentinels off newly-created records before they
 * reach the connector's create endpoint.
 */
export function clearRecordId(record: Record<string, unknown>, idPath: IdPath): void {
  unset(record, idPath);
}

/**
 * Build a fresh object containing only the id at its id path. Used to
 * construct id-only stubs for connector update/delete filters where the full
 * record body isn't needed (the connector reads the id leaf from the stub).
 */
export function recordWithId(idPath: IdPath, value: string | number): Record<string, unknown> {
  return set({}, idPath, value);
}

export type BaseJsonTableSpec = {
  id: EntityId;
  slug: string;
  name: string;
  schema: TSchema;
  /**
   * Lodash-style dot path into a record file that locates its remote id.
   * Most connectors use a flat `idPath('id')`; Attio uses `idPath('id.record_id')`
   * (and `idPath('id.entry_id')` for list entries) because its id is an object.
   * Read with `lodash/get`, never bracket access.
   */
  idColumnRemoteId: IdPath;
  // The remoteId of the column that should be used as the title/header column for visualizing records
  titleColumnRemoteId?: EntityId['remoteId'];
  // The remoteId of the column that should be used as the main content/body in MD view
  // This is used to display the main content of the record in the MD view.
  mainContentColumnRemoteId?: EntityId['remoteId'];
  // Lodash dot-path into a record for extracting a slug value used in filenames.
  // Example: 'fieldData.slug' for Webflow records.
  slugFieldPath?: string;
  /** @deprecated Use slugFieldPath instead */
  slugColumnRemoteId?: string;

  // The root path of this connector including any sites, bases, collections that should precede the table
  // For Webflow this would be the site name and collection name
  // For Airtable this would be the base name
  basePath?: string[];

  // The date and time the schema was generated
  // ISO 8601 format
  generatedAt?: string;
};

/**
 * Generic representation of a record file from a connector
 * This lets us know when we are talking about record files instead of using the generic Record<string, unknown> type.
 */
export type ConnectorFile = Record<string, unknown>;

export type ConnectorErrorDetails = {
  userFriendlyMessage: string;
  description?: string;
  additionalContext?: Record<string, unknown>;
};

export type RecordErrorsMetadata = {
  // TODO: Add record-level here if needed.

  /** Indexed by the WSID of the field */
  byField?: Record<string, { message: string; severity: 'warning' | 'error' }[]>;
};
