import { TSchema } from '@sinclair/typebox';
import type { DataFolderOptions, EntityId, TableView } from '@spinner/shared-types';
import { PostgresColumnType, X_SCRATCH_LAST_MODIFIED_FIELD } from '@spinner/shared-types';
import { get, set, unset } from 'lodash';
import { JsonSafeObject } from 'src/utils/objects';

// Re-export from shared-types for backwards compatibility
export { PostgresColumnType };
export type { EntityId };

export type TablePreview = {
  id: EntityId;
  displayName: string;
  /** The table is not available to be read from
   * e.g. A supabase table without a unique column.
   */
  disabled?: true;
  /** Tables that don't have an autogenerated id column — creates are not supported */
  disabledCreates?: true;
  /** Tables where existing records cannot be modified through this connector */
  disabledUpdates?: true;
  /** Tables where existing records cannot be removed through this connector */
  disabledDeletes?: true;
  /** Slash-separated path for grouping tables in the UI (e.g. "My Project/public") */
  parentPath?: string;
  /** Human-readable reason why this table is disabled or has writes disabled */
  disabledReason?: string;
  metadata?: Record<string, unknown>;
};

/**
 * A lodash-style dot path into a record file pointing at the value used as
 * its remote id (e.g. `'id'` for flat ids, `'id.record_id'` for Attio's id
 * triple). Branded so callers must construct it via `idPath(...)` and can't
 * accidentally pass a plain string.
 */
export type IdPath = string & { readonly __idPath: unique symbol };

/**
 * Construct an `IdPath` from a lodash-style dot path string. Use at every site
 * a connector schema declares its `idColumnRemoteId`.
 */
export function idPath(path: string): IdPath {
  return path as IdPath;
}

/**
 * Read the raw value at a record's id path. Preserves the native JSON type so
 * callers that need to detect special markers (e.g. pending-publish sentinels)
 * or write the value back into a file via `lodash.set` see exactly what's on
 * disk. Use `readRecordIdAsString` when you need a string for index/lookup.
 */
export function readRecordId(record: Record<string, unknown>, idPath: IdPath): unknown {
  return get(record, idPath);
}

/**
 * Read a record's id and coerce it to a string for use as a file-index key,
 * remote-id lookup, or filename. Returns `null` if the value at the path is
 * missing or is neither a string nor a finite number — callers that want a
 * string fallback typically write `readRecordIdAsString(...) ?? ''`.
 */
export function readRecordIdAsString(record: Record<string, unknown>, idPath: IdPath): string | null {
  const v = readRecordId(record, idPath);
  if (typeof v === 'string') return v;
  if (typeof v === 'number' && Number.isFinite(v)) return String(v);
  return null;
}

/**
 * Write a value at a record's id path. Mutates the record in place. Use when
 * recovering an id that was missing from the file content (filename-index
 * fallback) so the connector and git see a consistent value before the write.
 */
export function writeRecordId(record: Record<string, unknown>, idPath: IdPath, value: string | number): void {
  set(record, idPath, value);
}

/**
 * Remove the value at a record's id path. Mutates the record in place. Used
 * to strip pending-publish sentinels off newly-created records before they
 * reach the connector's create endpoint.
 */
export function clearRecordId(record: Record<string, unknown>, idPath: IdPath): void {
  unset(record, idPath);
}

/**
 * Build a fresh object containing only the id at its id path. Used to
 * construct id-only stubs for connector update/delete filters where the full
 * record body isn't needed (the connector reads the id leaf from the stub).
 */
export function recordWithId(idPath: IdPath, value: string | number): Record<string, unknown> {
  return set({}, idPath, value);
}

export type BaseJsonTableSpec = {
  id: EntityId;
  slug: string;
  name: string;
  schema: TSchema;
  /**
   * Lodash-style dot path into a record file that locates its remote id.
   * Most connectors use a flat `idPath('id')`; Attio uses `idPath('id.record_id')`
   * (and `idPath('id.entry_id')` for list entries) because its id is an object.
   * Read with `lodash/get`, never bracket access.
   */
  idColumnRemoteId: IdPath;
  // The remoteId of the column that should be used as the title/header column for visualizing records
  titleColumnRemoteId?: EntityId['remoteId'];
  // The remoteId of the column that should be used as the main content/body in MD view
  // This is used to display the main content of the record in the MD view.
  mainContentColumnRemoteId?: EntityId['remoteId'];
  // Lodash dot-path into a record for extracting a slug value used in filenames.
  // Example: 'fieldData.slug' for Webflow records.
  slugFieldPath?: string;
  /** @deprecated Use slugFieldPath instead */
  slugColumnRemoteId?: string;

  // The root path of this connector including any sites, bases, collections that should precede the table
  // For Webflow this would be the site name and collection name
  // For Airtable this would be the base name
  basePath?: string[];

  // The date and time the schema was generated
  // ISO 8601 format
  generatedAt?: string;

  // Default table view definition for the desktop app.
  // Written separately to views/default.json; stripped before writing schema.json.
  defaultView?: TableView;
};

/**
 * Generic representation of a record file from a connector
 * This lets us know when we are talking about record files instead of using the generic Record<string, unknown> type.
 */
export type ConnectorFile = Record<string, unknown>;

/**
 * The full options bag passed to `pullRecordFiles`. Extends the persisted
 * `DataFolderOptions` with non-persisted runtime fields set by the job at call
 * time so connectors can route between full and incremental pulls without a
 * second method signature.
 *
 * - `pullMode` absent or `'full'` ⇒ existing full-scan behavior; `since`/`cursor`
 *   are ignored.
 * - `pullMode === 'incremental'` ⇒ the connector should pull only records
 *   changed since `since` (or after the opaque `cursor` if it uses tokens).
 *   Only invoked when `supportsIncrementalPull(options)` returns true.
 */
export interface PullRecordFilesOptions extends DataFolderOptions {
  pullMode?: 'full' | 'incremental';
  since?: Date | null;
  cursor?: JsonSafeObject | null;
}

/**
 * Returned from `pullRecordFiles`. Empty (`{}`) for full pulls; populated by
 * connectors that ran incremental so the job can persist the new watermark
 * and/or cursor for the next run.
 */
export interface PullRecordFilesResult {
  newWatermark?: Date;
  newCursor?: JsonSafeObject | null;
}

/**
 * Walk the `fields` properties of a `BaseJsonTableSpec` schema and return the
 * name of the first field annotated with `x-scratch-last-modified-field`. Used
 * by connectors that auto-detect a server-side last-modified column when the
 * user hasn't explicitly set `DataFolderOptions.modifiedAtField`.
 *
 * The schema shape this walks is the standard connector record schema:
 * `{ properties: { fields: { properties: { <fieldName>: { ... } } } } }`.
 * Returns `undefined` if no such field exists or the schema shape doesn't match.
 */
export function findLastModifiedFieldName(tableSpec: BaseJsonTableSpec): string | undefined {
  const schema = tableSpec.schema as unknown as Record<string, unknown>;
  const properties = schema?.['properties'] as Record<string, unknown> | undefined;
  const fields = properties?.['fields'] as Record<string, unknown> | undefined;
  const fieldsProps = fields?.['properties'] as Record<string, unknown> | undefined;
  if (!fieldsProps) return undefined;
  for (const fieldName of Object.keys(fieldsProps)) {
    const fieldSchema = fieldsProps[fieldName];
    if (
      fieldSchema !== null &&
      typeof fieldSchema === 'object' &&
      (fieldSchema as Record<string, unknown>)[X_SCRATCH_LAST_MODIFIED_FIELD] === true
    ) {
      return fieldName;
    }
  }
  return undefined;
}

export type ConnectorErrorDetails = {
  userFriendlyMessage: string;
  description?: string;
  additionalContext?: Record<string, unknown>;
};

export type RecordErrorsMetadata = {
  // TODO: Add record-level here if needed.

  /** Indexed by the WSID of the field */
  byField?: Record<string, { message: string; severity: 'warning' | 'error' }[]>;
};
