# PROD RELEASE JOBS (Protects prod branch)
.release_prod_job:
  stage: deploy
  image:
    name: goreleaser/goreleaser:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  dependencies: []
  script:
    - chmod +x scratch-cli/scripts/release_public.sh
    - scratch-cli/scripts/release_public.sh $RELEASE_TYPE
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual
      allow_failure: true

# Auto-deploy patch release on every merge to prod
release-cli-patch:
  extends: .release_prod_job
  variables:
    RELEASE_TYPE: "patch"
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: on_success

release-cli-minor:
  extends: .release_prod_job
  variables:
    RELEASE_TYPE: "minor"

release-cli-major:
  extends: .release_prod_job
  variables:
    RELEASE_TYPE: "major"

# TEST RELEASE JOBS (master branch, excludes scheduled pipelines)
.release_test_job:
  stage: deploy
  image:
    name: goreleaser/goreleaser:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  dependencies: []
  script:
    - chmod +x scratch-cli/scripts/release_test.sh
    - scratch-cli/scripts/release_test.sh $RELEASE_TYPE
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
      when: manual
      allow_failure: true

# Auto-deploy patch release on every merge to master
release-cli-test-patch:
  extends: .release_test_job
  variables:
    RELEASE_TYPE: "patch"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

release-cli-test-minor:
  extends: .release_test_job
  variables:
    RELEASE_TYPE: "minor"

release-cli-test-major:
  extends: .release_test_job
  variables:
    RELEASE_TYPE: "major"
