import { TableDiscoveryMode } from '../enums/enums';
import { ConnectorSettingDefinition } from './dtos';
import { EntityId } from './fieldtypes';

/** A table/entity a connector can read from, as listed for the table picker. */
export interface TablePreview {
  id: EntityId;
  displayName: string;
  /** The table is not available to be read from (e.g. a Supabase table without a unique column). */
  disabled?: boolean;
  /** Tables that don't have an autogenerated id column — creates are not supported. */
  disabledCreates?: boolean;
  /** Tables where existing records cannot be modified through this connector. */
  disabledUpdates?: boolean;
  /** Tables where existing records cannot be removed through this connector. */
  disabledDeletes?: boolean;
  /** Slash-separated path for grouping tables in the UI (e.g. "My Project/public"). */
  parentPath?: string;
  /** Human-readable reason why this table is disabled or has writes disabled. */
  disabledReason?: string;
  metadata?: Record<string, unknown>;
}

/** Response for `GET .../connections/:id/tables`. */
export interface TableList {
  tables: TablePreview[];
  discoveryMode: TableDiscoveryMode;
  supportsFilters: boolean;
  supportsFieldSelection: boolean;
  advancedSettings: ConnectorSettingDefinition[];
}

/** Response for `GET .../connections/:id/tables/search`. */
export interface TableSearchResult {
  tables: TablePreview[];
  hasMore: boolean;
}

/**
 * A location where a connector can create a new table for the user — an
 * Airtable base, a Postgres schema, a Notion page, etc. The `id` is the remote
 * identifier the create-table flow passes back as the new table's parent; `name`
 * is the human-readable label shown in the picker. Intentionally minimal; add
 * fields here as the create-table UX needs them.
 */
export interface CreateDestination {
  id: string;
  name: string;
}

/** Response for `GET .../connections/:id/create-destinations`. */
export interface CreateDestinationList {
  destinations: CreateDestination[];
}

/** Response for `GET .../connections/:id/tables/schema` (client-facing view of a table spec). */
export interface TableSchemaPreview {
  id: EntityId;
  slug: string;
  name: string;
  schema: Record<string, unknown>;
  idColumnRemoteId: string;
  titleColumnRemoteId?: string[];
  mainContentColumnRemoteId?: string[];
  slugFieldPath?: string;
  /** @deprecated Use slugFieldPath */
  slugColumnRemoteId?: string;
}
