import { TableDiscoveryMode } from '../enums/enums';
import { ConnectorSettingDefinition } from './dtos';
import { EntityId } from './fieldtypes';

/** A table/entity a connector can read from, as listed for the table picker. */
export interface TablePreview {
  id: EntityId;
  displayName: string;
  /** The table is not available to be read from (e.g. a Supabase table without a unique column). */
  disabled?: boolean;
  /** Tables that don't have an autogenerated id column — creates are not supported. */
  disabledCreates?: boolean;
  /** Tables where existing records cannot be modified through this connector. */
  disabledUpdates?: boolean;
  /** Tables where existing records cannot be removed through this connector. */
  disabledDeletes?: boolean;
  /** Slash-separated path for grouping tables in the UI (e.g. "My Project/public"). */
  parentPath?: string;
  /** Human-readable reason why this table is disabled or has writes disabled. */
  disabledReason?: string;
  /**
   * Human-readable note shown as an info icon + tooltip next to the table in
   * the table pickers (web and desktop). For tables that need explanation
   * before being added — what the table contains, notable exclusions, cost
   * caveats (e.g. Notion's fixed "Page Tree" table). Unlike `disabledReason`,
   * the table is fully usable.
   */
  infoNote?: string;
  /**
   * The connector could not determine a column that uniquely identifies this
   * table's rows (e.g. a Postgres/Supabase VIEW with no provably-unique output
   * column, DEV-11136). The table is selectable, but creating a data folder
   * for it REQUIRES the user to choose an ID column: pickers must collect a
   * field choice and send it as `CreateDataFolderDto.idFieldOverride` — the
   * server rejects folder creation for a flagged table without it. Fetch the
   * candidate columns from `GET .../tables/schema` (`TableSchemaPreview.schema`
   * properties); its `idPathRequiresUserSelection` carries the same signal.
   */
  requiresIdFieldSelection?: boolean;
  metadata?: Record<string, unknown>;
}

/** Response for `GET .../connections/:id/tables`. */
export interface TableList {
  tables: TablePreview[];
  discoveryMode: TableDiscoveryMode;
  supportsFilters: boolean;
  supportsFieldSelection: boolean;
  advancedSettings: ConnectorSettingDefinition[];
  /** Connector-specific search-box placeholder (see ConnectorMetadata.tableSearchPlaceholder). */
  tableSearchPlaceholder?: string;
  /** Connector-specific empty-state copy for SEARCH and LIST modes (see ConnectorMetadata.tableSearchInstructions). */
  tableSearchInstructions?: string;
}

/** Response for `GET .../connections/:id/tables/search`. */
export interface TableSearchResult {
  tables: TablePreview[];
  hasMore: boolean;
}

/**
 * The container a table lives in on the external service — an Airtable base, a
 * Google Sheets spreadsheet, a Supabase project+schema, a Notion parent page.
 * The same place a {@link CreateDestination} names, but resolved for a table
 * that already exists, so a client can say "this table lives in <container>"
 * and link there.
 *
 * Cached rather than resolved live: a connector rebuilds it on every pull, the
 * same refresh that keeps the table's own name and `remoteWebUrl` current.
 */
export interface RemoteContainer {
  /** The container's remote id, in the same form a `CreateDestination.id` takes. */
  id: string;
  /** Display name. Never treat it as identity — that's `id`; a rename must follow. */
  name: string;
  /** Deep link on the SERVICE's site, or null when it has no constructible container link. */
  remoteWebUrl: string | null;
}

/**
 * A location where a connector can create a new table for the user — an
 * Airtable base, a Postgres schema, a Notion page, etc. The `id` is the remote
 * identifier the create-table flow passes back as the new table's parent; `name`
 * is the human-readable label shown in the picker. Intentionally minimal; add
 * fields here as the create-table UX needs them.
 */
export interface CreateDestination {
  id: string;
  name: string;
  /**
   * False for a destination that does not exist yet and will be provisioned on
   * the first create (Google Sheets' "new spreadsheet"), true for one that is
   * already there. This is what lets a UI render "will be created" WITHOUT
   * knowing any connector's sentinel id — frontends must never branch on a
   * service. Required so the compiler catches every construction site.
   */
  created: boolean;
  /**
   * A deep link that lands the user in this destination on the external
   * service's own web UI (e.g. https://airtable.com/{baseId}), so a client can
   * offer an "open in {service}" action. A URL on the SERVICE's site, not a
   * Scratch URL. Stamped by the REST layer from
   * `Connector.buildCreateDestinationRemoteWebUrl`, not set by connectors
   * directly. Absent when the service has no constructible container link, or
   * when the destination does not exist yet — omitted rather than guessed.
   */
  remoteWebUrl?: string;
}

/** Response for `GET .../connections/:id/create-destinations`. */
export interface CreateDestinationList {
  destinations: CreateDestination[];
  /**
   * True when the base list was capped and more destinations exist than are
   * returned here — a hint for the UI to prompt "type to search all pages".
   */
  hasMore?: boolean;
}

/** Response for `GET .../connections/:id/create-destinations/search`. */
export interface CreateDestinationSearchResult {
  destinations: CreateDestination[];
  /** True when matches were cut off at the cap. */
  hasMore: boolean;
}

/** Response for `GET .../connections/:id/create-destinations/lookup`. */
export interface CreateDestinationLookup {
  /**
   * The resolved destination, or `null` when the connection cannot access the id
   * (deleted, or the connection was reauthorized into a different account). A
   * `null` here is an explicit "the saved selection is stale"; a transport/server
   * failure surfaces as a normal error status instead, so callers can distinguish
   * "confirmed gone" from "could not verify".
   */
  destination: CreateDestination | null;
}

/** Response for `GET .../connections/:id/tables/schema` (client-facing view of a table spec). */
export interface TableSchemaPreview {
  id: EntityId;
  slug: string;
  name: string;
  schema: Record<string, unknown>;
  /** Lodash dot path to the record's remote id (e.g. `'id'`, `'id.record_id'`). */
  idPath: string;
  /**
   * True when `idPath` is NOT trustworthy: the connector could not determine a
   * uniquely-identifying column for this table (see
   * `TablePreview.requiresIdFieldSelection`) and `idPath` is only a legacy
   * fallback. Consumers must have the user pick an ID column from `schema`'s
   * properties and pass it as `idFieldOverride` when creating the data folder;
   * the override resolves the condition.
   */
  idPathRequiresUserSelection?: boolean;
  /** Lodash dot path to the title/header field (e.g. `'fields.Name'`). */
  titlePath?: string;
  /** Lodash dot path to the main content/body field. */
  mainContentPath?: string;
  /** Lodash dot path to the slug field. */
  slugPath?: string;
  /**
   * Declares that this table's records form a tree through an in-record parent
   * pointer (see `BaseJsonTableSpec.recordTree` on the server). Frontends use
   * it generically — e.g. to offer a tree view of the folder's records.
   */
  recordTree?: {
    /** Lodash dot path to the parent record's id (e.g. `'parent.page_id'`). */
    parentIdPath: string;
    /** Lodash dot path to the parent-kind discriminator (e.g. `'parent.type'`). */
    parentKindPath?: string;
    /** Lodash dot path to a record's own URL in the external service (e.g. `'url'`). */
    recordUrlPath?: string;
  };
  /** Free-text guidance for AI agents working with this folder's files (see server `BaseJsonTableSpec`). */
  agentInstructions?: string;
  /**
   * @deprecated DEV-10092 — superseded by `idPath`. A server predating the
   * path-field rename still sends this; readers should prefer `idPath` and fall
   * back to this during the transition.
   */
  idColumnRemoteId?: string;
  /** @deprecated DEV-10092 — superseded by `titlePath` (now a dot string; this was a segment array). */
  titleColumnRemoteId?: string[];
  /** @deprecated DEV-10092 — superseded by `mainContentPath` (now a dot string; this was a segment array). */
  mainContentColumnRemoteId?: string[];
  /** @deprecated DEV-10092 — superseded by `slugPath`. */
  slugFieldPath?: string;
  /** @deprecated Use slugPath */
  slugColumnRemoteId?: string;
}
