import { execSync } from "node:child_process";
import dotenv from "dotenv";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { probeStackHealth } from "./stack-health";
import { writeTestState } from "./test-state";

export default async function globalSetup() {
  // Load .env.integration (does not override existing env vars)
  dotenv.config({ path: path.resolve(__dirname, "../.env.integration") });

  const apiKey = process.env.SCRATCH_API_KEY;
  if (!apiKey) {
    throw new Error("SCRATCH_API_KEY environment variable is required");
  }

  const serverUrl = process.env.SCRATCH_API_URL || "http://localhost:3010";

  // 1. Resolve or build the CLI binary
  let binaryPath = process.env.SCRATCH_CLI_BINARY;
  if (!binaryPath) {
    const crateDir = path.resolve(__dirname, "../../scratch-git-2");
    console.log("Building scratchmd binary (Rust)...");
    execSync("cargo build --bin scratchmd --release", {
      cwd: crateDir,
      stdio: "inherit",
    });
    binaryPath = path.join(crateDir, "target", "release", "scratchmd");
  }

  // Verify binary exists and is executable
  execSync(`${binaryPath} --version`, { stdio: "pipe" });

  // 2. Write credentials file to an isolated temp HOME
  //    so tests don't interfere with the developer's real credentials
  const tempHome = fs.mkdtempSync(
    path.join(os.tmpdir(), "scratch-cli-test-home-"),
  );
  const credsDir = path.join(tempHome, ".scratchmd");
  fs.mkdirSync(credsDir, { recursive: true });

  // The CLI credentials.yaml format (v2): keyed by normalized server hostname
  const hostname = new URL(serverUrl).hostname;
  const credsContent = [
    "# Auto-generated by scratch-cli-tests",
    'version: "2.0.0"',
    "environments:",
    `  ${hostname}:`,
    `    apiToken: "${apiKey}"`,
    "",
  ].join("\n");

  fs.writeFileSync(path.join(credsDir, "credentials.yaml"), credsContent, {
    mode: 0o600,
  });

  // 3. Health check the target server, and record the build it is serving.
  //    The build version is the harness's deploy fingerprint: the settle gate
  //    in ScratchCli compares against it before dispatching async jobs, and
  //    global-teardown reports if it changed during the run.
  //    Deadline-based rather than a fixed attempt count, because each probe has
  //    its own timeout. The window is generous so a run that starts while the
  //    test-env is mid-rollout waits for it instead of failing at setup.
  const healthWaitBudgetMs = 120_000;
  const healthWaitDeadline = Date.now() + healthWaitBudgetMs;
  let buildVersionObservedAtGlobalSetup: string | null = null;
  let serverBecameHealthy = false;
  do {
    const probe = await probeStackHealth(serverUrl);
    if (probe.reachable) {
      buildVersionObservedAtGlobalSetup = probe.buildVersion;
      serverBecameHealthy = true;
      break;
    }
    await new Promise((r) => setTimeout(r, 500));
  } while (Date.now() < healthWaitDeadline);
  if (!serverBecameHealthy) {
    throw new Error(
      `Server at ${serverUrl} did not become healthy within ${healthWaitBudgetMs / 1000}s`,
    );
  }

  console.log(
    `[stack-health] ${serverUrl} is healthy, serving build ${buildVersionObservedAtGlobalSetup ?? "unknown"}.` +
      (buildVersionObservedAtGlobalSetup === null
        ? " No build version reported — deploy-collision detection is disabled for this run."
        : ""),
  );

  // Save state for test helpers and teardown
  writeTestState({
    binaryPath,
    serverUrl,
    tempHome,
    buildVersionObservedAtGlobalSetup,
    mostRecentlySettledBuildVersion: buildVersionObservedAtGlobalSetup,
  });
}
