import { execSync } from 'node:child_process';
import dotenv from 'dotenv';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const STATE_FILE = path.join(os.tmpdir(), 'scratch-cli-tests-state.json');

export default async function globalSetup() {
  // Load .env.integration (does not override existing env vars)
  dotenv.config({ path: path.resolve(__dirname, '../.env.integration') });

  const apiKey = process.env.SCRATCH_API_KEY;
  if (!apiKey) {
    throw new Error('SCRATCH_API_KEY environment variable is required');
  }

  const serverUrl = process.env.SCRATCH_API_URL || 'http://localhost:3010';

  // 1. Resolve or build the CLI binary
  let binaryPath = process.env.SCRATCH_CLI_BINARY;
  if (!binaryPath) {
    const cliDir = path.resolve(__dirname, '../../scratch-cli');
    console.log('Building scratchmd binary...');
    execSync('go build -o ./scratchmd ./cmd/scratchmd', { cwd: cliDir, stdio: 'inherit' });
    binaryPath = path.join(cliDir, 'scratchmd');
  }

  // Verify binary exists and is executable
  execSync(`${binaryPath} --version`, { stdio: 'pipe' });

  // 2. Write credentials file to an isolated temp HOME
  //    so tests don't interfere with the developer's real credentials
  const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'scratch-cli-test-home-'));
  const credsDir = path.join(tempHome, '.scratchmd');
  fs.mkdirSync(credsDir, { recursive: true });

  // The CLI credentials.yaml format (v2): keyed by normalized server hostname
  const hostname = new URL(serverUrl).hostname;
  const credsContent = [
    '# Auto-generated by scratch-cli-tests',
    'version: "2.0.0"',
    'environments:',
    `  ${hostname}:`,
    `    apiToken: "${apiKey}"`,
    '',
  ].join('\n');

  fs.writeFileSync(path.join(credsDir, 'credentials.yaml'), credsContent, { mode: 0o600 });

  // 3. Health check the target server
  const healthUrl = `${serverUrl}/health`;
  const maxAttempts = 30;
  for (let i = 0; i < maxAttempts; i++) {
    try {
      const res = await fetch(healthUrl);
      if (res.ok) break;
    } catch {
      // not ready
    }
    if (i === maxAttempts - 1) {
      throw new Error(`Server at ${serverUrl} did not become healthy within 15s`);
    }
    await new Promise((r) => setTimeout(r, 500));
  }

  // Save state for test helpers and teardown
  fs.writeFileSync(STATE_FILE, JSON.stringify({ binaryPath, serverUrl, tempHome }));
}
