stages:
  - test
  - build and test
  - release desktop app
  - push to prod
  - push images
  - pre-deploy environment tests
  - run migrations
  - deploy
  - post-deploy environment tests
  - deployment notifications
  - cleanup
